[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.ruff]
line-length = 120
lint.select = ["E", "F", "W", "C90"]
lint.ignore = ["E501"]
exclude = ["benchmarkthing"]
lint.per-file-ignores = { "__init__.py" = ["F401"] }
